name: "Deploy to GitHub Pages"

on:
  push:
    branches:
      - deploy
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read  # 读取仓库内容
  pages: write    # 写入 GitHub Pages
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the `deploy` branch
        uses: actions/checkout@v4
        with:
          ref: deploy  # 确保 checkout `deploy` 分支

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
